### ISSUE TITLE
[Bug]: Config Missing

### ISSUE THREAD

**Issue by Atlantispy** [someaddons/biomesizes#3]
### Describe the bug you're experiencing

I can't find where the config to adjust size of the biome is, I'd have asked on discord but it seems to be down?

### Reproducability

Launch with Biome Sizes installed, open config folder, cannot find config file.

### Mod up to date

- [x] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.2

### Modloader version

Forge

### Logs

https://gist.github.com/Atlantispy/b35348972956b7cfae18ed8d0963ce8d

**Comment by someaddons** [comment]
config is only on newer versions 1.19+

**Comment by Atlantispy** [comment]
I see! Sorry to be a pain, but is there a way to make the biomes bigger on 1.18 then? Currently it just goes for the smaller size and I wanted the mod for the opposite!

**Comment by Atlantispy** [comment]
I'd be willing to pay to get the config onto the 1.18 version if that helps!

**Comment by matzar24** [comment]
> config is only on newer versions 1.19+

I dont see any config in 1.19.2

**Comment by mateus3c** [comment]
yeah there is no config even on 1.19.2
