### ISSUE TITLE
[Bug]: SmallBiomes-1.3 (1.19.2 Forge) Config doesn't generate

### ISSUE THREAD

**Issue by ThatGuyJess** [someaddons/biomesizes#4]
### Describe the bug you're experiencing

Great mod, but the 1.3 version for 1.19.2 does not generating a config file.

The mod **does work** however and It's dependency mod, **cupboard**, how **does** generate a config. Small Biomes also works with other mods (Terralith, Tectonic, OBYG, WWOO) [which is awesome! Thanks!]

I can send you a list of my 12 mods, and/or my config folder if it's necessary.

### Reproducability

Play with Mod installed, config won't generate

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

N/A?

**Comment by DatLlama453** [comment]
How do u use this mod I have no idea how to. There is no tutorial and it won’t let me leave a comment either it says I need to put git hubs logs idk what that is either I’m just trynna use this mod 
![2F59D87D-2821-4CB0-B57A-F5C455282E3A](https://github.com/someaddons/biomesizes/assets/157789822/d4849d3b-c390-4921-88b2-4b4274b09a36)

**Comment by matzar24** [comment]
WHy cupboard is required as it was released way much later than small biomes mod???

**Comment by lavenderdotpet** [comment]
im having the same issue 
mod is installed but no config is generating
