### ISSUE TITLE
No tutorial 

### ISSUE THREAD

**Issue by DatLlama453** [someaddons/biomesizes#5]
### Describe the bug you're experiencing

I have no idea how to use this mod 

### Reproducability

Please produce a tutorial because I really like the idea of this mod but have no idea how to use it 
![5A907A5F-6C4D-4EAC-8F79-A23A552DD783](https://github.com/someaddons/biomesizes/assets/157789822/2ce01e10-a63c-4cb0-9e57-9e3dc726ff04)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

Java 

### Modloader version

Forge

### Logs

N/a

**Comment by someaddons** [comment]
increase the value to increase biome size, decrease to decrease biome size

**Comment by HTT155** [comment]
Which one of the numbers do I edit? Just the one after "BiomeSizeModifier": ? like how would I increase my biome sizes by like 5 times their size for all biomes just as a general example, assuming that this is possible?
