### ISSUE TITLE
Question/Suggestion

### ISSUE THREAD

**Issue by Tyrius1** [someaddons/biomesizes#6]
Would it be possible to make a minimum biome size without increase the average size?
Or potentially adding an additional config to set a minimum biome size.
I'd like to prevent biomes the size of 2 or 3 trees from generating while also increasing the average size of all biomes just slightly.

Also, would it be possible to say something like "X biome must always have Y biome bordering it." To say something like if beach isn't bordering ocean then do not generate beach. As sometimes random beach biomes will generate in the middle of a biome with no water bordering it.

**Comment by someaddons** [comment]
no the settings are all very indirect, can't really tell minecraft how to behave
