### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CapNapu** [someaddons/biomesizes#7]
### Describe the bug you're experiencing

Something that I noticed after installing this mod is that the mushroom fields don't seem to spawn at all. Either they don't generate, or are rare enough that the /locate command just stops working.

This bug also applies to any custom/datapack biome that uses the same worldgen rules as vanilla mushroom fields, like the Alpha Islands from Terralith.

### Reproducability

Set any value that isn't 0 in the config, generate a world with the seed ¨0¨, and then use /locate

(The log file includes a test using a 2 as the config value)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

[<script src="https://gist.github.com/CapNapu/f9de9c82ed4fdb8b097db48510484bcf.js"></script>](https://gist.github.com/CapNapu/f9de9c82ed4fdb8b097db48510484bcf)

**Comment by someaddons** [comment]
Mushroom fields are just very rare, even without the mod you'll often have the locate biome not finding any in its search range.
I made a vanilla world which could locate the biome and recreated one with the mod with the same seed and it did pick up the biome aswell, so not a bug :)
