### ISSUE TITLE
Not Sure How To Use. . .

### ISSUE THREAD

**Issue by Amber-09** [someaddons/biomesizes#8]
Sorry, I do not normally dig into the configuration of any mods, but for this one, I have to.

I am trying to set my world to only have plains and oceans, and I do not know how to achieve that. 

This was the only mod that I could find that had a recent update to at least the 1.20s. 

I read over the description, went to the patreon, reddit, youtube, couldn't find anything to explain this to me.

Sorry! Any help is appreciated

Edit: I found this mod under a reddit in search of some way to choose which biomes will and will not generate, so if that was wrong and I cannot use this mod to prevent biomes from generating, please let me know. Again, sorry!

**Comment by willydoesgit** [comment]
having the same problem. Can't find any information on how to actually use this mod. Never understood modders that spend hours making something but don't spend the extra little bit of time to make some documentation.

**Comment by mx776** [comment]
How to use:
I added it to my modpack so for me it's under *yourusername*\curseforge\minecraft\Instances\ *yourmodpack*\config
...where you will find the biomesize.json file which you can open in a text editor.

**Comment by someaddons** [comment]
This mod is for altering the size of the biome, not which biomes can spawn, that'd be a vanilla datapack :D
And yes the config does have a description, if you cannot find the config well then its not just this mod you got issues with.
